# Generated by Django 4.0.6 on 2023-01-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('waste_type', models.CharField(choices=[('SOLID', 'SOLID'), ('LIQUID', 'LIQUID')], max_length=100)),
                ('waste_weight', models.CharField(max_length=50)),
                ('added_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
