# Generated by Django 4.0.6 on 2023-01-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
