# Generated by Django 4.0.6 on 2023-02-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_waste_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='waste_type',
            field=models.CharField(choices=[('SOLID ', 'solid waste'), ('LIQUID', 'liquid waste'), ('HAZARDOUS', 'hazardous waste'), ('ORGANIC', 'organic waste')], max_length=100),
        ),
    ]
