# Generated by Django 4.0.6 on 2023-02-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_waste_waste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='added_date',
            field=models.DateField(),
        ),
    ]
