# Generated by Django 4.0.6 on 2023-02-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_waste_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='added_date',
            field=models.DateField(blank=True),
        ),
    ]
